const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const productsSchema = new Schema({
  availableForPurchase: String,
  basePrice: Number,
  category: String,
  changeTaxCode: Boolean,
  chargeTaxes: Boolean,
  collections: String,
  description: String,
  isAvailable: Boolean,
  isAvailableForPurchase: Boolean,
  isPublished: Boolean,
  name: String,
  productType: String,
  publicationDate: String,
  seoDescription: String,
  seoTitle: String,
  sku: String,
  slug: String,
  stockQuantity: Number,
  taxCode: String,
  trackInventory: Boolean,
  visibleInListings: Boolean,
  weight: String,
});
module.exports = mongoose.model('Products', productsSchema);

// availableForPurchase: "Yes",
//   basePrice: 10000,
//   category: "Fashion testing",
//   changeTaxCode: "TAX",
//   chargeTaxes: true,
//   collections: "TESTING COLLECTION",
//   description: "This is a testing products out there",
//   isAvailable: true,
//   isAvailableForPurchase: false,
//   isPublished: false,
//   name: "testing name",
//   productType: "freindly testing",
//   publicationDate: "10/02/2020",
//   seoDescription: "testing seo description",
//   seoTitle: "testing a seo title",
//   sku:"GHJ",
//   slug: "ASD",
//   stockQuantity:30,
//   taxCode:"WER",
//   trackInventory: true,
//   visibleInListings: true,
//   weight: "50 kg",
